### ISSUE TITLE
Multiple folders?

### ISSUE THREAD

**Issue by K4Z3R0** [Lightjohn/CbXManager#1]
Is it possible to create cbz out of multiple folders?

**Comment by Lightjohn** [comment]
Not sure to understand what you mean.
Seems that if you use [regroupImages.py](https://github.com/Lightjohn/CbXManager/blob/master/regroupImages.py) with a high limits it should do the trick?

**Comment by K4Z3R0** [comment]
> Not sure to understand what you mean.
> Seems that if you use [regroupImages.py](https://github.com/Lightjohn/CbXManager/blob/master/regroupImages.py) with a high limits it should do the trick?

If possible, I'd like to create a batch of cbz files by selecting multiple folders in a row. Because I have a large number of folders to convert to cbz but can only do so one at a time.

**Comment by Lightjohn** [comment]
So if you have lets say:
```
folderA
folderA
folderA
```

**Comment by Lightjohn** [comment]
In that case what prevent you from running `regroupImages.py` with the folders you want as input and a limit set to 100000
This will create one cbz from some folder and then run it again with others folders?

You will have to change the structure of your folder before:
```
BigFolder1:
  folder1
  folder2
  folder3
BigFolder2:
  folder4
  folder5
  folder6
```
and run manually: 
`python regroupImages.py --limit 100000 BigFolder1`
then
`python regroupImages.py --limit 100000 BigFolder2`

This code is quite old and lack many options but with a very simple wrapper script you could process whatever you want else it will be manual but that should still work.

**Comment by K4Z3R0** [comment]
That's kind of what I wanted, but I wanted it to keep the folder name and the number of files inside the folder while converting it to cbz.

**Comment by Lightjohn** [comment]
Yeahh the script is far too basic sadly...
It was made a long time ago.
