### ISSUE TITLE
not working on  windows

### ISSUE THREAD

**Issue by migube** [Lightjohn/CbXManager#3]
hoi
due to \ /difference , a cbz with a folder with files  fails under python under windows

will try linux tomorrow

**Comment by Lightjohn** [comment]
Bit strange, if I remember well there should be no / in my code.
Had a quick look and found one.

Can you tell me how did you launched the scripts? Thanks

**Comment by migube** [comment]
hoi

python cbxmanager.py ccc.cbz -v

looking at the error, maybe it's a double \\ issue (see below) not the /

the cbz file contains one comicinfo.xml then one folder, and under the folder the image files

It creates the folder ccc , that's ok
then 
  File "C:\Users\chris\Downloads\CbXManager-master\CbXManager-master\cbxmanager.py", line 77, in parse_cbz
    with open(path_out + self.sep + name, "wb") as tmp_img:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: "ccc\\04 - Un txxx/"

tx!

**Comment by Lightjohn** [comment]
Indeed the folder inside is causing an issue!
Looking at it!

**Comment by Lightjohn** [comment]
A fix has been pushed, should solve your issue :)

**Comment by migube** [comment]
that was quick :)
indeed it does!
tx
