### ISSUE TITLE
Some comments & potential additional features :)

### ISSUE THREAD

**Issue by migube** [Lightjohn/CbXManager#4]
hi again

some comments & questions :)
images = ["png", "jpg", "jpeg"] => could also be webp I assume ?

Some command line options that could make sense
- extract only the  images (from above list of types), not any other files , could eg help to remove  comicinfo.xml (or other  non image file) & write back archive?
- extract  only the  first  and/or the last  X/Y files (assuming X<total files (image files or other depending on above), ) 
(something like 
            nrfiles=len(files_to_extract)
            if (i<=nrfiles and i<=x) or (i>=nrfiles-Y and i<=nrfiles):  then write the files

the idea is to get a sample of the first x & last y pages 

let me know if it makes sense/q's
tx !

**Comment by Lightjohn** [comment]
Hello :)

Webp is supported by pillow: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp
But it needs additional local library which would not work by default on windows.

I do not develop that library except for bugs so adding specific features is difficult.

For your first case:
I would do
```
python cbxmanager.py test.cbz
rm */*.xml
python cbxmanager.py test/
```

The second case is more specific and not sure I can emulate that :) 

Also don't forget that cbz are simply zip files so quite easy to manipulate with usual zip tools 

https://github.com/Lightjohn/CbXManager/blob/master/cbxmanager.py#L67

With just that for loop you can easily do what you want.

First suggestion is doable, second seems too specific.

**Comment by migube** [comment]
Tx lightjohn,

correct for first case :)

For webp, I don't specifically need it, just saying in case of.

For second case, yes I got it already working with the changes above inside the loop, so for me's it's not an issue, just if u wanted more features for others, then it needs to be clean in the code, while mine is just quick & dirty  (no error checks, no cli options, just hardcoded :)

tx

**Comment by Lightjohn** [comment]
As long as it works everything is good :)
thanks for the feedback and good luck

**Comment by migube** [comment]
:) just  tried  one one with multiple  folders inside, there it  fails :)   arghh, I'll  see what I do with  it :-p (and check that your version is ok there first)

**Comment by Lightjohn** [comment]
Indeed I see, I tried on Linux and I found the bug.

But it also seems that I intentionally made that extracting will bring all files inside folder at top level folder.
That is intentional because folders in cbz are randomly supported so not a really good idea.

**Comment by migube** [comment]
agreed, usually I split the subfolders to one folder per  cbz only ,   still doing  manually  though as I don't  have so many like  that

**Comment by Lightjohn** [comment]
I just saw that this message was never sent..

Indeed I see, I tried on Linux and I found the bug.

But it also seems that I intentionally made that extracting will bring all files inside folder at top level folder.
That is intentional because folders in cbz are randomly supported so not a really good idea.
